/**
 * Tests for the wrapper-drift doctor check (#140).
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import fs from 'fs';
import path from 'path';
import os from 'os';

import {
  compareVersions,
  makeWrapperDriftCheck,
} from '../src/doctor/checks/wrapper-drift.js';
import type { DoctorContext } from '../src/doctor/types.js';

describe('compareVersions', () => {
  it('returns -1 when a < b', () => {
    expect(compareVersions('1.18.7', '1.19.0')).toBe(-1);
    expect(compareVersions('1.19.0', '1.19.1')).toBe(-1);
    expect(compareVersions('1.19', '1.19.1')).toBe(-1);
  });

  it('returns 1 when a > b', () => {
    expect(compareVersions('1.20.0', '1.19.9')).toBe(1);
    expect(compareVersions('2.0.0', '1.99.99')).toBe(1);
  });

  it('returns 0 on equality', () => {
    expect(compareVersions('1.19.0', '1.19.0')).toBe(0);
    expect(compareVersions('1.19', '1.19.0')).toBe(0);
  });

  it('returns 0 on malformed input', () => {
    expect(compareVersions('not-a-version', '1.0.0')).toBe(0);
  });
});

describe('wrapperDriftCheck', () => {
  let workDir: string;
  let scriptPath: string;
  let crontabFile: string;

  beforeEach(() => {
    workDir = fs.mkdtempSync(path.join(os.tmpdir(), 'mk-doctor-drift-'));
    scriptPath = path.join(workDir, 'memory-sync.sh');
    crontabFile = path.join(workDir, 'crontab.txt');
  });

  afterEach(() => {
    fs.rmSync(workDir, { recursive: true, force: true });
  });

  function writeWrapper(generatorVersion: string): void {
    fs.writeFileSync(scriptPath, [
      '#!/usr/bin/env bash',
      `# mk:generator-version=${generatorVersion}`,
      '# mk:memory-dir=/foo',
      '# mk:claude-md=/bar',
      '# mk:memory-repo=/foo',
      '# mk:max-tokens=16000',
      '# mk:agent-id=$(hostname -s)',
      'mk render /foo /bar',
    ].join('\n'));
    fs.writeFileSync(crontabFile, `0 23 * * * ${scriptPath}\n`);
  }

  function ctx(): DoctorContext {
    return {
      memoryDir: workDir,
      kernelVersion: '1.19.4',
      skipCategories: new Set(),
      env: { MK_CRONTAB_FILE: crontabFile },
    };
  }

  it('passes when wrapper version matches binary version', () => {
    writeWrapper('1.19.4');
    const check = makeWrapperDriftCheck({
      discoverOptions: { home: workDir, userCrontabFile: crontabFile, skipSystem: true },
    });
    const result = check.run(ctx()) as Awaited<ReturnType<typeof check.run>>;
    expect(result.ok).toBe(true);
    expect(result.issues).toEqual([]);
  });

  it('flags a wrapper generated by an older mk version', () => {
    writeWrapper('1.18.7');
    const check = makeWrapperDriftCheck({
      discoverOptions: { home: workDir, userCrontabFile: crontabFile, skipSystem: true },
    });
    const result = check.run(ctx()) as Awaited<ReturnType<typeof check.run>>;
    expect(result.ok).toBe(false);
    expect(result.issues).toHaveLength(1);
    expect(result.issues[0]).toContain('v1.18.7');
    expect(result.issues[0]).toContain('v1.19.4');
    expect(result.issues[0]).toContain('mk init --cron --update');
  });

  it('does NOT flag a wrapper that is somehow ahead of the binary', () => {
    // Useful when running a dev build against wrappers regenerated against
    // a newer release tag — we don't want to nag the user about that.
    writeWrapper('1.20.0');
    const check = makeWrapperDriftCheck({
      discoverOptions: { home: workDir, userCrontabFile: crontabFile, skipSystem: true },
    });
    const result = check.run(ctx()) as Awaited<ReturnType<typeof check.run>>;
    expect(result.ok).toBe(true);
  });

  it('returns ok when no mk-generated wrappers are found', () => {
    // No crontab, no scripts.
    const check = makeWrapperDriftCheck({
      discoverOptions: { home: workDir, userCrontabFile: crontabFile, skipSystem: true },
    });
    const result = check.run(ctx()) as Awaited<ReturnType<typeof check.run>>;
    expect(result.ok).toBe(true);
  });

  // Untracked wrappers — hand-rolled scripts that call mk but lack the
  // # mk:generator-version= header. Mai's ~/mk-memory/memory-sync.sh on
  // 2026-05-19 was exactly this shape: working, but invisible to the
  // version-drift comparison until it gets regenerated via mk init --cron.
  it('flags a hand-rolled wrapper that calls mk but has no mk: header', () => {
    fs.writeFileSync(scriptPath, [
      '#!/usr/bin/env bash',
      '# Memory sync — reflect, render to NanoClaw, commit & push.',
      'set -euo pipefail',
      'mk reflect -d /foo --agent-id my-agent --session-id sync-test',
      'mk render /foo /bar --max-tokens 16000',
    ].join('\n'));
    fs.writeFileSync(crontabFile, `0 23 * * * ${scriptPath}\n`);

    const check = makeWrapperDriftCheck({
      discoverOptions: { home: workDir, userCrontabFile: crontabFile, skipSystem: true },
    });
    const result = check.run(ctx()) as Awaited<ReturnType<typeof check.run>>;
    expect(result.ok).toBe(false);
    expect(result.issues).toHaveLength(1);
    expect(result.issues[0]).toContain(scriptPath);
    expect(result.issues[0]).toContain('hand-rolled');
    expect(result.issues[0]).toContain('mk init --cron');
  });

  it('flags both kinds in one run', () => {
    const handRolledPath = path.join(workDir, 'old-wrapper.sh');
    fs.writeFileSync(handRolledPath, '#!/bin/bash\nmk render /a /b\n');
    writeWrapper('1.18.7'); // mk-generated at older version
    // Append the hand-rolled wrapper to the crontab as well.
    fs.appendFileSync(crontabFile, `0 4 * * * ${handRolledPath}\n`);

    const check = makeWrapperDriftCheck({
      discoverOptions: { home: workDir, userCrontabFile: crontabFile, skipSystem: true },
    });
    const result = check.run(ctx()) as Awaited<ReturnType<typeof check.run>>;
    expect(result.ok).toBe(false);
    expect(result.issues).toHaveLength(2);
    const joined = result.issues.join('\n');
    expect(joined).toContain('v1.18.7');
    expect(joined).toContain('hand-rolled');
  });
});
