/**
 * wrapper-drift check — uses discoverWrappers() to find mk-generated scripts
 * (those with the `# mk:generator-version=` header from #143), then flags any
 * whose embedded version is older than the kernel binary on PATH.
 *
 * This is the most concrete drift signal we have. If a wrapper was generated
 * by mk 1.18.7 and the binary is now 1.19.4, the wrapper may be using flags
 * that have changed or defaults that have shifted — exactly the situation
 * that broke Mai's memory-sync.sh on the 1.18.9 upgrade.
 */

import {
  discoverWrappers,
  type DiscoveredWrapper,
  type DiscoverOptions,
} from '../discover-wrappers.js';
import { parseGeneratedHeader } from '../../cron-template.js';
import type { Check, CheckResult, DoctorContext } from '../types.js';

/**
 * Compare two semver-ish strings. Returns -1/0/1 (a vs b). Treats malformed
 * inputs as equal (we don't fail the check on a weird version string).
 */
export function compareVersions(a: string, b: string): -1 | 0 | 1 {
  const parse = (s: string) => s.split('.').map((p) => parseInt(p, 10));
  const x = parse(a);
  const y = parse(b);
  if (x.some(Number.isNaN) || y.some(Number.isNaN)) return 0;
  for (let i = 0; i < Math.max(x.length, y.length); i += 1) {
    const xi = x[i] ?? 0;
    const yi = y[i] ?? 0;
    if (xi < yi) return -1;
    if (xi > yi) return 1;
  }
  return 0;
}

export interface WrapperDriftCheckOptions {
  /** Override discoverWrappers options (e.g. for tests). */
  discoverOptions?: DiscoverOptions;
}

export function makeWrapperDriftCheck(
  opts: WrapperDriftCheckOptions = {},
): Check {
  return {
    name: 'wrapper-drift',
    category: 'wrappers',
    defaultSeverity: 'warn',
    skipWhen: ['wrappers', 'cron'],
    run(ctx: DoctorContext): CheckResult {
      const wrappers = discoverWrappers(opts.discoverOptions);
      const issues: string[] = [];

      for (const w of wrappers as readonly DiscoveredWrapper[]) {
        // We only care about scripts that look like wrapper FILES, not the
        // user crontab itself. discoverWrappers labels the user crontab
        // source as the literal "crontab -l" string; everything else is a
        // file path. (When MK_CRONTAB_FILE is used, the source is that
        // absolute path, which is correctly treated as a real wrapper if
        // it happens to look like one — but that's a deliberate testing
        // path, not a production one.)
        if (w.source === 'crontab -l') continue;

        if (w.isMkGenerated) {
          const header = parseGeneratedHeader(w.content);
          if (!header) continue;
          const cmp = compareVersions(header.generatorVersion, ctx.kernelVersion);
          if (cmp < 0) {
            issues.push(
              `${w.source}: generated by mk v${header.generatorVersion}, binary is v${ctx.kernelVersion} — run \`mk init --cron --update --output ${w.source}\``,
            );
          }
          continue;
        }

        // Hand-rolled wrapper: calls mk but has no `# mk:generator-version=`
        // header. We can't compare versions against anything, but we can
        // surface it as untracked — the user is one binary upgrade away
        // from silent breakage, and `mk init --cron` would normalize it.
        issues.push(
          `${w.source}: hand-rolled wrapper (no mk: header) — regenerate with \`mk init --cron\` so future drift can be detected`,
        );
      }

      return {
        name: 'wrapper-drift',
        category: 'wrappers',
        severity: 'warn',
        ok: issues.length === 0,
        issues,
      };
    },
  };
}

export const wrapperDriftCheck: Check = makeWrapperDriftCheck();
