/**
 * cron-template — pure generator for the canonical memory-sync wrapper (#143).
 *
 * `mk init --cron` calls into here. Keeping generation pure (no FS, no
 * Date.now) lets us snapshot-test it deterministically and lets the CLI layer
 * own crontab/file-system side effects.
 *
 * The generated script embeds machine-parseable `# mk:KEY=VALUE` header lines
 * so `mk init --cron --update` can re-read the original paths without making
 * the user re-type them, and `mk doctor` (#140) can detect wrapper-vs-binary
 * version drift.
 */

import path from 'path';

export interface CronWrapperOptions {
  /** Absolute path to the memory directory. */
  memoryDir: string;
  /** Absolute path the rendered CLAUDE.md should be written to. */
  claudeMd: string;
  /** Absolute path to the git repo to commit/push from. Defaults to dirname(memoryDir). */
  memoryRepo?: string;
  /** Token budget passed to `mk render --max-tokens`. Default 16000. */
  maxTokens?: number;
  /**
   * Agent ID passed to `mk reflect --agent-id`. When omitted the generated
   * script uses `$(hostname -s)` so the same script works across hosts.
   */
  agentId?: string;
  /** Kernel version string for the header, e.g. `1.19.3`. */
  kernelVersion: string;
  /**
   * ISO-8601 timestamp for the header. Injected (not generated internally)
   * so snapshot tests stay deterministic.
   */
  generatedAt: string;
}

/** Prefix used for machine-parseable header lines. */
const HEADER_PREFIX = '# mk:';

/** Default render token budget — matches mk render's own default. */
export const DEFAULT_MAX_TOKENS = 16000;

interface MachineHeader {
  generatorVersion: string;
  generatedAt: string;
  memoryDir: string;
  claudeMd: string;
  memoryRepo: string;
  maxTokens: number;
  agentId: string | null; // null means "use $(hostname -s) at run time"
}

function resolveDefaults(opts: CronWrapperOptions): MachineHeader {
  return {
    generatorVersion: opts.kernelVersion,
    generatedAt: opts.generatedAt,
    memoryDir: opts.memoryDir,
    claudeMd: opts.claudeMd,
    memoryRepo: opts.memoryRepo ?? path.dirname(opts.memoryDir),
    maxTokens: opts.maxTokens ?? DEFAULT_MAX_TOKENS,
    agentId: opts.agentId ?? null,
  };
}

/**
 * Generate the canonical wrapper script. Returns the full file contents
 * including shebang and trailing newline. Caller is responsible for writing
 * to disk and chmod +x.
 */
export function generateCronWrapper(opts: CronWrapperOptions): string {
  validate(opts);
  const h = resolveDefaults(opts);

  const headerLines = [
    '#!/usr/bin/env bash',
    `# Canonical memory-sync wrapper for memory-kernel.`,
    `# Generated by mk v${h.generatorVersion}.`,
    `# Regenerate in place with: mk init --cron --update --output <this-file>`,
    `# Do not edit the "${HEADER_PREFIX}" lines below — they are read by mk doctor.`,
    `${HEADER_PREFIX}generator-version=${h.generatorVersion}`,
    `${HEADER_PREFIX}generated-at=${h.generatedAt}`,
    `${HEADER_PREFIX}memory-dir=${h.memoryDir}`,
    `${HEADER_PREFIX}claude-md=${h.claudeMd}`,
    `${HEADER_PREFIX}memory-repo=${h.memoryRepo}`,
    `${HEADER_PREFIX}max-tokens=${h.maxTokens}`,
    `${HEADER_PREFIX}agent-id=${h.agentId ?? '$(hostname -s)'}`,
  ];

  const body = [
    '',
    '# Fail-soft by design: we deliberately do NOT use `set -e`. Each step is',
    '# guarded so one non-fatal failure (e.g. a grep that legitimately exits 1 on',
    '# no-match) can never silently kill the whole nightly sync — that exact bug',
    '# left a fleet dark for 6 days (#303). `-u` and pipefail stay on.',
    'set -uo pipefail',
    '',
    "# Make mk resolvable under cron's minimal PATH. mk installs alongside node,",
    '# and `npm i -g`/`--user` installs land in ~/.local/bin — prepend both so the',
    '# wrapper finds `mk` even when cron strips the interactive PATH (#303).',
    'export PATH="$(dirname "$(command -v node 2>/dev/null || echo /usr/bin/node)"):$HOME/.local/bin:$PATH"',
    '',
    '# Paths — embedded by mk init --cron. Override at runtime by exporting',
    '# the matching MK_* env var (useful for testing without regenerating).',
    `MEMORY_DIR="${'$'}{MK_MEMORY_DIR:-${h.memoryDir}}"`,
    `CLAUDE_MD="${'$'}{MK_CLAUDE_MD:-${h.claudeMd}}"`,
    `MEMORY_REPO="${'$'}{MK_MEMORY_REPO:-${h.memoryRepo}}"`,
    `MAX_TOKENS="${'$'}{MK_MAX_TOKENS:-${h.maxTokens}}"`,
    h.agentId
      ? `AGENT_ID="${'$'}{MK_AGENT_ID:-${h.agentId}}"`
      : `AGENT_ID="${'$'}{MK_AGENT_ID:-$(hostname -s)}"`,
    `SESSION_ID="sync-$(date -u +%Y%m%dT%H%M%SZ)"`,
    '',
    'mk_sync_warnings=0',
    'log() { echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] mk-sync: $*"; }',
    '# step <description> <cmd...> — run a step guarded; a failure is logged and',
    '# counted but never aborts the sync (the #303 fail-soft contract).',
    'step() {',
    '  local desc="$1"; shift',
    '  if "$@"; then log "$desc ok"; else log "WARN: $desc failed (continuing)"; mk_sync_warnings=$((mk_sync_warnings + 1)); fi',
    '}',
    '',
    '# Step 1: consolidate (dedup, TTL, promote, detect conflicts).',
    'step "reflect" mk reflect -d "$MEMORY_DIR" --agent-id "$AGENT_ID" --session-id "$SESSION_ID"',
    '',
    '# Step 2: reindex WITH embeddings so new atoms get vectors before render/recall.',
    '# Skipping this is why agents hit "key set, 0 vectors" — see `mk doctor`',
    '# embeddings-vectors-fresh (#305). No-op (cheap) when no embedding key is set.',
    'step "reindex --embed" mk reindex -d "$MEMORY_DIR" --embed',
    '',
    '# Step 3: render CLAUDE.md from active atoms.',
    'step "render" mk render -d "$MEMORY_DIR" -o "$CLAUDE_MD" --max-tokens "$MAX_TOKENS"',
    '',
    '# Step 4: commit + push if the rendered output (or any tracked file) changed.',
    '#',
    '# git add -A picks up every untracked file under MEMORY_REPO. If this',
    '# wrapper script itself lives inside MEMORY_REPO, add its filename to',
    '# .gitignore so it does not get committed alongside the memory data.',
    'cd "$MEMORY_REPO" || { log "ERROR: cannot cd to $MEMORY_REPO"; exit 1; }',
    'if [ -n "$(git status --porcelain)" ]; then',
    `  step "git commit+push" bash -c 'git add -A && git commit -m "memory: sync $(date -u +%Y-%m-%dT%H:%MZ)" && git push'`,
    'else',
    '  log "no changes to commit"',
    'fi',
    '',
    '# Step 5: self-canary — a non-fatal health probe AFTER the sync. `mk doctor`',
    '# exits non-zero on warn/error (e.g. 0 vectors, stale sync); we surface that',
    '# in the cron log so a silent breakage gets noticed, but never abort on it (#303).',
    'canary_out="${TMPDIR:-/tmp}/mk-sync-doctor.$$"',
    'if mk doctor -d "$MEMORY_DIR" > "$canary_out" 2>&1; then',
    '  log "canary: mk doctor clean"',
    'else',
    '  log "WARN: canary flagged issues (mk doctor):"',
    '  sed "s/^/    /" "$canary_out"',
    '  mk_sync_warnings=$((mk_sync_warnings + 1))',
    'fi',
    'rm -f "$canary_out"',
    '',
    'if [ "$mk_sync_warnings" -eq 0 ]; then',
    '  log "sync complete"',
    'else',
    '  log "sync complete WITH $mk_sync_warnings warning(s) — see above"',
    'fi',
    '',
  ];

  return [...headerLines, ...body].join('\n');
}

function validate(opts: CronWrapperOptions): void {
  if (!path.isAbsolute(opts.memoryDir)) {
    throw new Error(`memoryDir must be an absolute path (got: ${opts.memoryDir})`);
  }
  if (!path.isAbsolute(opts.claudeMd)) {
    throw new Error(`claudeMd must be an absolute path (got: ${opts.claudeMd})`);
  }
  if (opts.memoryRepo !== undefined && !path.isAbsolute(opts.memoryRepo)) {
    throw new Error(`memoryRepo must be an absolute path (got: ${opts.memoryRepo})`);
  }
  if (opts.maxTokens !== undefined && (!Number.isInteger(opts.maxTokens) || opts.maxTokens <= 0)) {
    throw new Error(`maxTokens must be a positive integer (got: ${opts.maxTokens})`);
  }
  if (!/^[\d.]+/.test(opts.kernelVersion)) {
    throw new Error(`kernelVersion looks malformed: ${opts.kernelVersion}`);
  }
  if (Number.isNaN(Date.parse(opts.generatedAt))) {
    throw new Error(`generatedAt must be a parseable ISO timestamp (got: ${opts.generatedAt})`);
  }
}

/**
 * Parse the machine-readable `# mk:KEY=VALUE` header lines out of a generated
 * wrapper script. Used by `mk init --cron --update` to recover the original
 * paths so the user doesn't have to retype them.
 *
 * Tolerant of files that aren't mk-generated — returns null if no header
 * found. Stops at the first non-blank, non-comment line so it doesn't pick
 * up `# mk:` strings embedded later in the script body.
 */
export function parseGeneratedHeader(content: string): MachineHeader | null {
  const found: Partial<Record<string, string>> = {};

  for (const rawLine of content.split('\n')) {
    const line = rawLine.trim();
    if (line === '' || line.startsWith('#!')) continue;
    if (!line.startsWith('#')) break;
    if (!line.startsWith(HEADER_PREFIX)) continue;
    const rest = line.slice(HEADER_PREFIX.length);
    const eq = rest.indexOf('=');
    if (eq < 0) continue;
    found[rest.slice(0, eq).trim()] = rest.slice(eq + 1).trim();
  }

  if (
    !found['generator-version']
    || !found['memory-dir']
    || !found['claude-md']
  ) {
    return null;
  }

  const maxTokens = found['max-tokens'] ? parseInt(found['max-tokens'], 10) : DEFAULT_MAX_TOKENS;
  const agentIdRaw = found['agent-id'] ?? '';
  // `$(hostname -s)` sentinel means "no fixed agent ID" — preserve that.
  const agentId = agentIdRaw && agentIdRaw !== '$(hostname -s)' ? agentIdRaw : null;

  return {
    generatorVersion: found['generator-version'],
    generatedAt: found['generated-at'] ?? '',
    memoryDir: found['memory-dir'],
    claudeMd: found['claude-md'],
    memoryRepo: found['memory-repo'] ?? path.dirname(found['memory-dir']),
    maxTokens: Number.isInteger(maxTokens) && maxTokens > 0 ? maxTokens : DEFAULT_MAX_TOKENS,
    agentId,
  };
}

/**
 * Idempotently append a crontab line to a file. If a line referencing the
 * same target script already exists, replace it instead of appending a
 * duplicate. Returns the final contents — caller writes back via
 * `crontab -` (or, in tests, against a temp file via the MK_CRONTAB_FILE
 * override that the CLI consults).
 *
 * Pure function: takes the current crontab text + the new line, returns
 * new text. Identifies "the same entry" by a whole-token match of the
 * target script path — the path must appear bounded by characters that
 * cannot belong to a filesystem path (whitespace, quotes, line ends).
 * A trailing `.bak`, `-disabled`, or any path-continuation suffix means
 * it's a different script and is left alone.
 */
export function applyCrontabLine(
  current: string,
  scheduleAndScript: string,
  scriptPath: string,
): string {
  const lines = current.split('\n');
  let replaced = false;
  const next: string[] = [];
  const scriptTokenRe = scriptPathTokenRegex(scriptPath);

  for (const line of lines) {
    // If a non-comment line contains the script path as a whole shell token,
    // treat it as the existing entry and replace it. Avoids duplicate entries
    // when --install-cron is run twice with the same --output, but does not
    // clobber siblings like `.../sync.sh.bak` whose path is a strict superset.
    if (
      line.trim() !== ''
      && !line.trim().startsWith('#')
      && scriptTokenRe.test(line)
    ) {
      if (!replaced) {
        next.push(scheduleAndScript);
        replaced = true;
      }
      continue;
    }
    next.push(line);
  }

  if (!replaced) {
    // Append before any trailing blank line for tidiness.
    while (next.length > 0 && next[next.length - 1] === '') next.pop();
    next.push(scheduleAndScript);
    next.push('');
  }

  return next.join('\n');
}

/**
 * Build a regex that matches `scriptPath` only when it appears as a whole
 * shell token — i.e. not adjacent on either side to characters that could
 * legitimately extend the path (`[A-Za-z0-9._/-]`). This is the boundary
 * rule we want for crontab lines: `/p/sync.sh` matches in
 * `* * * * * /p/sync.sh`, `"/p/sync.sh"`, and `/p/sync.sh --arg`, but not
 * in `/p/sync.sh.bak` or `/p/sync.sh-disabled`.
 */
function scriptPathTokenRegex(scriptPath: string): RegExp {
  const escaped = scriptPath.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return new RegExp(`(?<![A-Za-z0-9._/\\-])${escaped}(?![A-Za-z0-9._/\\-])`);
}
